version: 2.0
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
  test:
    docker:
      - image: circleci/node:12.2.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: 
          name: Run unit tests
          command: npm test
  deploy:
    docker:
      - image: circleci/node:12.2.0
    environment: 
      HEROKU_APP: greetings-api-jj
    steps: 
      - checkout
      - run:
          name: Deploy to Heroku
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git master


workflows:
  version: 2
  build_and_test:
    jobs: 
      - build
      - test
      - deploy:  
          type: approval
          requires:
            - build
            - test